includes:
  - configs/s2ef/MD22/datasets/base.yml

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/MD22/95_lmdb/DHA/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -27383.035
          stdev: 0.41342595
        forces:
          mean: 0
          stdev: 1.1258113
  val:
    src: /data/shared/MLFF/MD22/95_lmdb/DHA/val/
