includes:
  - configs/s2ef/MD22/datasets/AT-AT/base.yml
  - configs/s2ef/MD22/EScAIP/base/L6_H8_512_.yml

model:
  backbone:
    batch_size: 32
    max_num_nodes_per_batch: 64
optim:
  batch_size: 32
  eval_batch_size: 24
  eval_every: 500
  max_epochs: 10000
  lr_initial: 0.00004
